import React from 'react'
import { Clock } from 'lucide-react'
import { SubtaskList } from './SubtaskList'
import type { Subtask } from '../../store/tasksSlice'

interface TaskDetailContentProps {
    title: string
    setTitle: (v: string) => void
    description: string
    setDescription: (v: string) => void
    priority: 'very-low' | 'low' | 'medium' | 'high' | 'very-high'
    setPriority: (v: 'very-low' | 'low' | 'medium' | 'high' | 'very-high') => void

    startDate: string
    setStartDate: (v: string) => void
    startHour: number
    setStartHour: (v: number) => void
    startMinute: number
    setStartMinute: (v: number) => void

    dueDate: string
    setDueDate: (v: string) => void
    endHour: number
    setEndHour: (v: number) => void
    endMinute: number
    setEndMinute: (v: number) => void

    reminderEnabled: boolean
    setReminderEnabled: (v: boolean) => void
    reminderDate: string
    setReminderDate: (v: string) => void
    reminderHour: number
    setReminderHour: (v: number) => void
    reminderMinute: number
    setReminderMinute: (v: number) => void

    autoGenerateDaily: boolean
    setAutoGenerateDaily: (v: boolean) => void

    // Subtask props
    subtasks: (Subtask | Omit<Subtask, 'id' | 'task_id' | 'order'>)[]
    pendingSubtaskUpdates: Record<string, Partial<Subtask>>
    onUpdateSubtask: (index: number, id: string | undefined, updates: Partial<Subtask>) => void
    onDeleteSubtask: (id: string | undefined, index: number) => void
    onAddSubtask: (subtask: Omit<Subtask, 'id' | 'task_id' | 'order'>) => void
}

export const TaskDetailContent: React.FC<TaskDetailContentProps> = (props) => {
    const {
        title, setTitle,
        description, setDescription,
        priority, setPriority,
        startDate, setStartDate,
        startHour, setStartHour,
        startMinute, setStartMinute,
        dueDate, setDueDate,
        endHour, setEndHour,
        endMinute, setEndMinute,
        reminderEnabled, setReminderEnabled,
        reminderDate, setReminderDate,
        reminderHour, setReminderHour,
        reminderMinute, setReminderMinute,
        autoGenerateDaily, setAutoGenerateDaily,
        subtasks, pendingSubtaskUpdates, onUpdateSubtask, onDeleteSubtask, onAddSubtask
    } = props

    return (
        <div className="flex-1 overflow-y-auto px-3 py-2 space-y-3">
            {/* 标题 */}
            <div>
                <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">任务标题</label>
                <input
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="输入任务标题..."
                    className="w-full px-2 py-1.5 text-sm bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 focus:border-transparent transition-all dark:text-gray-100 dark:placeholder-gray-500"
                    autoFocus
                />
            </div>

            {/* 描述 */}
            <div>
                <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">描述</label>
                <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="添加任务描述..."
                    rows={2}
                    className="w-full px-2 py-1.5 text-sm bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 focus:border-transparent transition-all resize-none dark:text-gray-200 dark:placeholder-gray-500"
                />
            </div>

            {/* 开始日期时间和截止日期时间 - 垂直排列 */}
            <div className="space-y-2">
                {/* 开始日期时间 */}
                <div>
                    <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">开始日期</label>
                    <div className="flex gap-1.5">
                        <input
                            type="date"
                            value={startDate}
                            onChange={(e) => {
                                const newStartDate = e.target.value
                                setStartDate(newStartDate)
                                if (newStartDate > dueDate) {
                                    setDueDate(newStartDate)
                                }
                            }}
                            className="flex-1 min-w-0 px-2 h-[30px] text-sm bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 transition-all cursor-pointer dark:text-gray-200 dark:placeholder-gray-500 dark:color-scheme-dark"
                            style={{ position: 'relative', zIndex: 10, pointerEvents: 'auto' }}
                        />
                        <select
                            value={startHour}
                            onChange={(e) => setStartHour(parseInt(e.target.value))}
                            className="w-14 px-1 h-[30px] text-xs bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200"
                        >
                            {Array.from({ length: 24 }, (_, i) => (
                                <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                            ))}
                        </select>
                        <span className="text-gray-400 self-center text-sm font-medium">:</span>
                        <select
                            value={startMinute}
                            onChange={(e) => setStartMinute(parseInt(e.target.value))}
                            className="w-14 px-1 h-[30px] text-xs bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200"
                        >
                            {Array.from({ length: 60 }, (_, i) => (
                                <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                            ))}
                        </select>
                    </div>
                </div>
                {/* 截止日期时间 */}
                <div>
                    <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">截止日期</label>
                    <div className="flex gap-1.5">
                        <input
                            type="date"
                            value={dueDate}
                            onChange={(e) => {
                                const newDate = e.target.value
                                setDueDate(newDate)
                                if (newDate < startDate) {
                                    setStartDate(newDate)
                                }
                            }}
                            className="flex-1 min-w-0 px-2 h-[30px] text-sm bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 transition-all cursor-pointer dark:text-gray-200 dark:placeholder-gray-500 dark:color-scheme-dark"
                            style={{ position: 'relative', zIndex: 10, pointerEvents: 'auto' }}
                        />
                        <select
                            value={endHour}
                            onChange={(e) => setEndHour(parseInt(e.target.value))}
                            className="w-14 px-1 h-[30px] text-xs bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200"
                        >
                            {Array.from({ length: 24 }, (_, i) => (
                                <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                            ))}
                        </select>
                        <span className="text-gray-400 self-center text-sm font-medium">:</span>
                        <select
                            value={endMinute}
                            onChange={(e) => setEndMinute(parseInt(e.target.value))}
                            className="w-14 px-1 h-[30px] text-xs bg-white/50 dark:bg-gray-800/50 border border-white/40 dark:border-gray-600 rounded-lg outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200"
                        >
                            {Array.from({ length: 60 }, (_, i) => (
                                <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                            ))}
                        </select>
                    </div>
                </div>
            </div>

            {/* Continuous Task Option */}
            {(() => {
                const isContinuous = startDate !== dueDate
                if (isContinuous) {
                    return (
                        <div className="flex items-center gap-2 p-2 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-100 dark:border-purple-800/50">
                            <div className="flex-1">
                                <div className="text-xs font-medium text-purple-800 dark:text-purple-300">这是持续任务</div>
                                <div className="text-[10px] text-purple-600 dark:text-purple-400/80">是否每日自动添加任务到"今日待办"？</div>
                            </div>
                            <div className="flex items-center gap-2">
                                <span className={`text-xs ${!autoGenerateDaily ? 'font-bold text-gray-600 dark:text-gray-300' : 'text-gray-400 dark:text-gray-600'}`}>否</span>
                                <button
                                    onClick={() => setAutoGenerateDaily(!autoGenerateDaily)}
                                    className={`relative w-8 h-4 rounded-full transition-colors ${autoGenerateDaily ? 'bg-purple-500' : 'bg-gray-300 dark:bg-gray-600'}`}
                                >
                                    <div className={`absolute top-0.5 w-3 h-3 bg-white rounded-full shadow transition-transform ${autoGenerateDaily ? 'translate-x-4' : 'translate-x-0.5'}`}></div>
                                </button>
                                <span className={`text-xs ${autoGenerateDaily ? 'font-bold text-purple-600 dark:text-purple-400' : 'text-gray-400 dark:text-gray-600'}`}>是</span>
                            </div>
                        </div>
                    )
                }
                return null
            })()}

            {/* 提醒设置 - 紧凑版 */}
            <div>
                <div className="flex items-center gap-2 mb-2">
                    <button
                        onClick={() => setReminderEnabled(!reminderEnabled)}
                        className={`relative w-8 h-4 rounded-full transition-colors ${reminderEnabled ? 'bg-blue-500' : 'bg-gray-300 dark:bg-gray-600'}`}
                    >
                        <div className={`absolute top-0.5 w-3 h-3 bg-white rounded-full shadow transition-transform ${reminderEnabled ? 'translate-x-4' : 'translate-x-0.5'}`}></div>
                    </button>
                    <span className="text-xs text-gray-600 dark:text-gray-400 flex items-center gap-1">
                        <Clock size={12} /> {reminderEnabled ? '提醒开启' : '提醒关闭'}
                    </span>
                </div>
                {reminderEnabled && (
                    <div className="grid grid-cols-3 gap-2 p-2 bg-blue-50/50 dark:bg-blue-900/10 rounded-lg border border-blue-100 dark:border-blue-800/30">
                        <div>
                            <label className="block text-[10px] text-gray-500 dark:text-gray-400 mb-0.5">日期</label>
                            <input
                                type="date"
                                value={reminderDate}
                                onChange={(e) => setReminderDate(e.target.value)}
                                className="w-full px-1 py-0.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded text-xs outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200 dark:color-scheme-dark"
                            />
                        </div>
                        <div>
                            <label className="block text-[10px] text-gray-500 dark:text-gray-400 mb-0.5">时</label>
                            <select
                                value={reminderHour}
                                onChange={(e) => setReminderHour(parseInt(e.target.value))}
                                className="w-full px-1 py-0.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded text-xs outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200 py-1"
                            >
                                {Array.from({ length: 24 }, (_, i) => (
                                    <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                                ))}
                            </select>
                        </div>
                        <div>
                            <label className="block text-[10px] text-gray-500 dark:text-gray-400 mb-0.5">分</label>
                            <select
                                value={reminderMinute}
                                onChange={(e) => setReminderMinute(parseInt(e.target.value))}
                                className="w-full px-1 py-0.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded text-xs outline-none focus:ring-1 focus:ring-blue-400 dark:text-gray-200 py-1"
                            >
                                {Array.from({ length: 60 }, (_, i) => (
                                    <option key={i} value={i} className="dark:bg-gray-800">{String(i).padStart(2, '0')}</option>
                                ))}
                            </select>
                        </div>
                    </div>
                )}
            </div>

            {/* 紧急程度 */}
            <div className="flex items-center gap-2">
                <span className="text-xs text-gray-500">优先级</span>
                <div className="flex gap-1.5">
                    {(['very-low', 'low', 'medium', 'high', 'very-high'] as const).map(p => {
                        const colors: Record<string, string> = {
                            'very-low': 'bg-gray-400',
                            low: 'bg-green-500',
                            medium: 'bg-yellow-500',
                            high: 'bg-red-500',
                            'very-high': 'bg-red-800'
                        }
                        return (
                            <button
                                key={p}
                                onClick={() => setPriority(p)}
                                className={`w-5 h-5 rounded-full border-2 ${colors[p]} ${priority === p ? 'ring-2 ring-offset-1 ring-blue-400' : 'opacity-50 hover:opacity-100'} transition-all`}
                                title={p}
                            />
                        )
                    })}
                </div>
            </div>

            <SubtaskList
                subtasks={subtasks}
                pendingSubtaskUpdates={pendingSubtaskUpdates}
                onUpdateSubtask={onUpdateSubtask}
                onDeleteSubtask={onDeleteSubtask}
                onAddSubtask={onAddSubtask}
                parentStartDate={startDate}
                parentStartHour={startHour}
                parentStartMinute={startMinute}
                parentDueDate={dueDate}
                parentDueHour={endHour}
                parentDueMinute={endMinute}
            />
        </div>
    )
}
